version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./vw-data:/data
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: ${DOMAIN_HTTPS}

  caddy:
    image: detroitenglish/docker-caddy-rpi:latest
    restart: always
    volumes:
      - ./caddy-data/config/Caddyfile:/etc/Caddyfile:ro
      - caddycerts:/root/.caddy
    ports:
      - 80:80
      - 443:443
    environment:
      ACME_AGREE: ${ACME_AGREE}
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
volumes:
  caddycerts: